{{- if .Values.motionTools }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "motion-tools.fullname" . }}
  labels:
    {{- include "motion-tools.labels" . | nindent 4 }}
data:
  config.json: |
    {
      "resourceBase": "/",
      "databaseType": "mysql",
      "db": {
        "dsn": "mysql:host={{ include "motion-tools.databaseHost" . }};dbname={{ include "motion-tools.databaseName" . }};charset=utf8mb4",
        "username": "{{ include "motion-tools.databaseUser" . }}",
        "password": "DB_PASSWORD_PLACEHOLDER"
      },
      "debug": {{ .Values.debug | default false }},

      {{- if .Values.motionTools.smtp.enabled }}
      "mailFromName": "{{ .Values.motionTools.smtp.from | default "Motion Tools" }}",
      "mailFromEmail": "{{ .Values.motionTools.smtp.from | default "noreply@example.com" }}",
      "mailService": {
        "transport": "smtp",
        "host": "{{ .Values.motionTools.smtp.host }}",
        "port": {{ .Values.motionTools.smtp.port }},
        "username": "{{ .Values.motionTools.smtp.user }}",
        "password": "SMTP_PASSWORD_PLACEHOLDER"
      },
      {{- else }}
      "mailFromName": "Motion Tools sendmail",
      "mailFromEmail": "noreply@example.com",
      "mailService": {
        "transport": "sendmail"
      },
      {{- end }}

      {{- if .Values.motionTools.valkey.enabled }}
      "redis": {
        "hostname": "{{ include "motion-tools.valkeyHost" . }}",
        "port": {{ .Values.motionTools.valkey.port | default 6379 }},
        "database": {{ .Values.motionTools.valkey.database | default 0 }}
        {{- if .Values.motionTools.valkey.password }},
        "password": "REDIS_PASSWORD_PLACEHOLDER"
        {{- end }}
      },
      {{- end }}

      {{- if .Values.motionTools.jwt.enabled }}
      "jwtPrivateKey": "{{ .Values.motionTools.jwt.privateKeyPath }}",
      {{- end }}

      {{- if .Values.motionTools.backgroundJobs.enabled }}
      "backgroundJobs": {
        "notifications": {{ .Values.motionTools.backgroundJobs.notifications | default true }}
      },
      {{- if .Values.motionTools.backgroundJobs.healthCheckKey }}
      "healthCheckKey": "{{ .Values.motionTools.backgroundJobs.healthCheckKey }}",
      {{- end }}
      {{- end }}

      {{- if .Values.motionTools.pdfRendering.engine }}
      {{- if eq .Values.motionTools.pdfRendering.engine "weasyprint" }}
      "weasyprintPath": "{{ .Values.motionTools.pdfRendering.weasyprintPath }}",
      {{- else if eq .Values.motionTools.pdfRendering.engine "latex" }}
      "lualatexPath": "{{ .Values.motionTools.pdfRendering.lualatexPath }}",
      "pdfunitePath": "{{ .Values.motionTools.pdfRendering.pdfunitePath }}",
      {{- end }}
      {{- end }}

      {{- if .Values.motionTools.imageMagick.enabled }}
      "imageMagickPath": "{{ .Values.motionTools.imageMagick.path }}",
      {{- end }}

      "dbConnection": "mysql",
      "confirmEmailAddresses": true,
      "domainPlain": "https://{{ .Values.motionTools.apacheFqdn }}/",
      "domainSubdomain": "https://{{ .Values.motionTools.apacheFqdn }}/",
      "siteBehaviorClasses": ["\\app\\models\\settings\\AntragsgruenApp"],
      "tmpDir": "/tmp/"
    }
{{- end }}
