{{- if or (and (not .Values.mariadb.enabled) (not .Values.externalDatabase.existingSecret)) (and .Values.motionTools.smtp.enabled (not .Values.motionTools.smtp.existingSecret)) (and .Values.motionTools.valkey.enabled .Values.motionTools.valkey.password (not .Values.motionTools.valkey.existingSecret)) (and .Values.motionTools.liveServer.enabled .Values.motionTools.liveServer.rabbitMqPassword (not .Values.motionTools.liveServer.rabbitMqExistingSecret)) -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "motion-tools.fullname" . }}
  labels:
    {{- include "motion-tools.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if and (not .Values.mariadb.enabled) (not .Values.externalDatabase.existingSecret) }}
  {{- if .Values.externalDatabase.password }}
  {{ .Values.externalDatabase.userPasswordKey | default "db-password" }}: {{ .Values.externalDatabase.password | b64enc | quote }}
  {{- end }}
  {{- end }}
  
  {{- if and .Values.motionTools.smtp.enabled (not .Values.motionTools.smtp.existingSecret) }}
  {{- if .Values.motionTools.smtp.password }}
  {{ .Values.motionTools.smtp.secretKey }}: {{ .Values.motionTools.smtp.password | b64enc | quote }}
  {{- end }}
  {{- end }}
  
  {{- if and .Values.motionTools.valkey.enabled .Values.motionTools.valkey.password (not .Values.motionTools.valkey.existingSecret) }}
  {{ .Values.motionTools.valkey.secretKey }}: {{ .Values.motionTools.valkey.password | b64enc | quote }}
  {{- end }}
  
  {{- if and .Values.motionTools.liveServer.enabled .Values.motionTools.liveServer.rabbitMqPassword (not .Values.motionTools.liveServer.rabbitMqExistingSecret) }}
  {{ .Values.motionTools.liveServer.rabbitMqSecretKey }}: {{ .Values.motionTools.liveServer.rabbitMqPassword | b64enc | quote }}
  {{- end }}
{{- end }}

{{- if and (not .Values.mariadb.enabled) (not .Values.externalDatabase.existingSecret) .Values.externalDatabase.password }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "motion-tools.fullname" . }}-db
  labels:
    {{- include "motion-tools.labels" . | nindent 4 }}
type: Opaque
data:
  {{ .Values.externalDatabase.userPasswordKey | default "db-password" }}: {{ .Values.externalDatabase.password | b64enc | quote }}
{{- end }}

{{- if and .Values.motionTools.smtp.enabled (not .Values.motionTools.smtp.existingSecret) .Values.motionTools.smtp.password }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "motion-tools.fullname" . }}-smtp
  labels:
    {{- include "motion-tools.labels" . | nindent 4 }}
type: Opaque
data:
  {{ .Values.motionTools.smtp.secretKey }}: {{ .Values.motionTools.smtp.password | b64enc | quote }}
{{- end }}

{{- if and .Values.motionTools.valkey.enabled .Values.motionTools.valkey.password (not .Values.motionTools.valkey.existingSecret) }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "motion-tools.fullname" . }}-valkey
  labels:
    {{- include "motion-tools.labels" . | nindent 4 }}
type: Opaque
data:
  {{ .Values.motionTools.valkey.secretKey }}: {{ .Values.motionTools.valkey.password | b64enc | quote }}
{{- end }}

{{- if and .Values.motionTools.liveServer.enabled .Values.motionTools.liveServer.rabbitMqPassword (not .Values.motionTools.liveServer.rabbitMqExistingSecret) }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "motion-tools.fullname" . }}-rabbitmq
  labels:
    {{- include "motion-tools.labels" . | nindent 4 }}
type: Opaque
data:
  {{ .Values.motionTools.liveServer.rabbitMqSecretKey }}: {{ .Values.motionTools.liveServer.rabbitMqPassword | b64enc | quote }}
{{- end }}