{{- if or (and (not .Values.app.existingSecretRandomSeed) .Values.app.randomSeed) (and .Values.app.smtp.enabled (not .Values.app.smtp.existingSecret)) (and .Values.app.oidc.enabled (not .Values.app.oidc.existingSecret)) -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "motion-tools.fullname" . }}-app
  labels:
    {{- include "motion-tools.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if and (not .Values.app.existingSecretRandomSeed) .Values.app.randomSeed }}
  random-seed: {{ .Values.app.randomSeed | b64enc | quote }}
  {{- end }}
  {{- if and .Values.app.smtp.enabled (not .Values.app.smtp.existingSecret) }}
  {{- if .Values.app.smtp.password }}
  smtp-password: {{ .Values.app.smtp.password | b64enc | quote }}
  {{- end }}
  {{- if not .Values.app.mailerDsn }}
  {{- $dsn := "" -}}
  {{- if and .Values.app.smtp.username .Values.app.smtp.password -}}
  {{- $dsn = printf "smtp://%s:%s@%s:%v" .Values.app.smtp.username .Values.app.smtp.password .Values.app.smtp.host .Values.app.smtp.port -}}
  {{- else -}}
  {{- $dsn = printf "smtp://%s:%v" .Values.app.smtp.host .Values.app.smtp.port -}}
  {{- end }}
  mailer-dsn: {{ $dsn | b64enc | quote }}
  {{- end }}
  {{- end }}
  {{- if and .Values.app.oidc.enabled (not .Values.app.oidc.existingSecret) }}
  {{- if .Values.app.oidc.clientId }}
  {{ .Values.app.oidc.clientIdSecretKey | default "oidc-client-id" }}: {{ .Values.app.oidc.clientId | b64enc | quote }}
  {{- end }}
  {{- if .Values.app.oidc.clientSecret }}
  {{ .Values.app.oidc.clientSecretSecretKey | default "oidc-client-secret" }}: {{ .Values.app.oidc.clientSecret | b64enc | quote }}
  {{- end }}
  {{- if .Values.app.oidc.groupMapping }}
  {{ .Values.app.oidc.groupMappingSecretKey | default "oidc-group-mapping" }}: {{ .Values.app.oidc.groupMapping | b64enc | quote }}
  {{- end }}
  {{- end }}
{{- end }}

{{- if and (not .Values.mariadb.enabled) (not .Values.externalDatabase.existingSecret) .Values.externalDatabase.password }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "motion-tools.fullname" . }}-db
  labels:
    {{- include "motion-tools.labels" . | nindent 4 }}
type: Opaque
data:
  {{ .Values.externalDatabase.userPasswordKey | default "db-password" }}: {{ .Values.externalDatabase.password | b64enc | quote }}
{{- end }}

{{- if and .Values.valkey.enabled .Values.valkey.auth.password (not .Values.valkey.auth.existingSecret) }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "motion-tools.fullname" . }}-valkey
  labels:
    {{- include "motion-tools.labels" . | nindent 4 }}
type: Opaque
data:
  {{ .Values.valkey.auth.existingSecretPasswordKey | default "password" }}: {{ .Values.valkey.auth.password | b64enc | quote }}
{{- end }}
