apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "motion-tools.fullname" . }}
  labels:
    {{- include "motion-tools.labels" . | nindent 4 }}
spec:
  replicas: 1
  serviceName: {{ include "motion-tools.fullname" . }}
  revisionHistoryLimit: {{ .Values.revisionHistoryLimit }}
  selector:
    matchLabels:
      {{- include "motion-tools.selectorLabels" . | nindent 6 }}
  {{- with .Values.updateStrategy }}
  updateStrategy:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  template:
    metadata:
      annotations:
        checksum/secret: {{ include (print $.Template.BasePath "/secret.yaml") . | sha256sum }}
        {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      labels:
        {{- include "motion-tools.labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "motion-tools.serviceAccountName" . }}
      {{- with .Values.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.priorityClassName }}
      priorityClassName: {{ . }}
      {{- end }}
      initContainers:
        {{- with .Values.initContainers }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
        {{- if .Values.motionTools.smtp.enabled }}
        # Init container to fix msmtprc template by adding auth line
        # This fixes the missing "auth login" line in the Docker image template
        - name: fix-msmtp-template
          image: {{ include "motion-tools.image" . }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command:
            - sh
            - -c
            - |
              echo "Fixing msmtprc template to add auth line..."
              if [ -f /templates/msmtprc.j2 ] && ! grep -q "^auth" /templates/msmtprc.j2; then
                sed -i '/^password {{ "{{" }} SMTP_PASS {{ "}}" }}/a \\nauth     login' /templates/msmtprc.j2
                echo "Auth line added to msmtprc template!"
              else
                echo "Auth line already exists or template not found."
              fi
          resources:
            limits:
              cpu: 100m
              memory: 128Mi
            requests:
              cpu: 50m
              memory: 64Mi
        {{- end }}
        {{- if .Values.persistence.enabled }}
        # Init container to copy application files from the Docker image to the persistent volume
        # This is needed because unlike docker-compose, Kubernetes PersistentVolumes start empty
        # and don't automatically populate from the image. This only runs on first deployment.
        - name: install-app
          image: {{ include "motion-tools.image" . }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command:
            - sh
            - -c
            - |
              # Only copy if the persistent volume is empty (first run)
              if [ ! -f /data/index.php ]; then
                echo "Initializing persistent volume with application files..."
                cp -a /var/www/html/. /data/
                echo "Application files copied to persistent volume!"
              else
                echo "Persistent volume already initialized, skipping."
              fi
          volumeMounts:
            - name: data
              mountPath: /data
          resources:
            limits:
              cpu: 200m
              memory: 256Mi
            requests:
              cpu: 100m
              memory: 128Mi
        {{- end }}
        {{- if .Values.mariadb.enabled }}
        - name: wait-for-database
          image: busybox:1.36
          imagePullPolicy: IfNotPresent
          {{- with .Values.securityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          command:
            - sh
            - -c
            - |
              until nc -z {{ include "motion-tools.databaseHost" . }} {{ include "motion-tools.databasePort" . }}; do
                echo "Waiting for database to be ready..."
                sleep 5
              done
              echo "Database is ready!"
              exit 0
          resources:
            limits:
              cpu: 100m
              memory: 128Mi
            requests:
              cpu: 50m
              memory: 64Mi
        {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          {{- with .Values.securityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          image: {{ include "motion-tools.image" . }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.targetPort }}
              protocol: TCP
          {{- if .Values.motionTools.smtp.enabled }}
          lifecycle:
            postStart:
              exec:
                command:
                  - /bin/sh
                  - -c
                  - |
                    # Wait for msmtprc to be created by entrypoint, then add auth line
                    for i in $(seq 1 30); do
                      if [ -f /etc/msmtprc ]; then
                        if ! grep -q "^auth" /etc/msmtprc; then
                          sed -i '/^password/a auth     login' /etc/msmtprc
                          echo "Added auth line to /etc/msmtprc"
                        fi
                        break
                      fi
                      sleep 1
                    done
          {{- end }}
          env:
            # Timezone configuration
            - name: TIMEZONE
              value: {{ .Values.motionTools.timezone | quote }}

            # Apache configuration
            - name: APACHE_FQDN
              value: {{ .Values.motionTools.apacheFqdn | quote }}

            {{- if .Values.motionTools.smtp.enabled }}
            # SMTP configuration
            - name: SMTP_HOST
              value: {{ .Values.motionTools.smtp.host | quote }}
            - name: SMTP_PORT
              value: {{ .Values.motionTools.smtp.port | quote }}
            - name: SMTP_FROM
              value: {{ .Values.motionTools.smtp.from | quote }}
            - name: SMTP_USER
              value: {{ .Values.motionTools.smtp.user | quote }}
            - name: SMTP_PASS
              valueFrom:
                secretKeyRef:
                  name: {{ include "motion-tools.smtpSecretName" . }}
                  key: {{ .Values.motionTools.smtp.secretKey }}
            {{- if .Values.motionTools.smtp.tls }}
            - name: SMTP_TLS
              value: "true"
            {{- end }}
            {{- end }}

            {{- with .Values.motionTools.extraEnvVars }}
            {{- toYaml . | nindent 12 }}
            {{- end }}

          {{- with .Values.motionTools.extraEnvFrom }}
          envFrom:
            {{- toYaml . | nindent 12 }}
          {{- end }}

          {{- if .Values.livenessProbe }}
          livenessProbe:
            {{- toYaml .Values.livenessProbe | nindent 12 }}
          {{- end }}

          {{- if .Values.readinessProbe }}
          readinessProbe:
            {{- toYaml .Values.readinessProbe | nindent 12 }}
          {{- end }}

          {{- if .Values.startupProbe }}
          startupProbe:
            {{- toYaml .Values.startupProbe | nindent 12 }}
          {{- end }}

          {{- with .Values.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}

          volumeMounts:
            - name: data
              mountPath: {{ .Values.persistence.mountPath | default "/var/www/html" }}
              {{- if .Values.persistence.subPath }}
              subPath: {{ .Values.persistence.subPath }}
              {{- end }}
            - name: php-config
              mountPath: /usr/local/etc/php/conf.d/php.ini
              subPath: php.ini

            {{- with .Values.extraVolumeMounts }}
            {{- toYaml . | nindent 12 }}
            {{- end }}

        {{- with .Values.sidecarContainers }}
        {{- toYaml . | nindent 8 }}
        {{- end }}

      volumes:
        - name: php-config
          configMap:
            name: {{ include "motion-tools.fullname" . }}-php-config
        {{- with .Values.extraVolumes }}
        {{- toYaml . | nindent 8 }}
        {{- end }}

      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}

      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}

      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}

      {{- with .Values.topologySpreadConstraints }}
      topologySpreadConstraints:
        {{- toYaml . | nindent 8 }}
      {{- end }}
  {{- if .Values.persistence.enabled }}
  volumeClaimTemplates:
    - metadata:
        name: data
        {{- with .Values.persistence.annotations }}
        annotations:
          {{- toYaml . | nindent 10 }}
        {{- end }}
      spec:
        accessModes:
          - {{ .Values.persistence.accessMode }}
        {{- if .Values.persistence.storageClass }}
        {{- if (eq "-" .Values.persistence.storageClass) }}
        storageClassName: ""
        {{- else }}
        storageClassName: {{ .Values.persistence.storageClass | quote }}
        {{- end }}
        {{- end }}
        resources:
          requests:
            storage: {{ .Values.persistence.size | quote }}
        {{- if .Values.persistence.selector }}
        selector:
          {{- toYaml .Values.persistence.selector | nindent 10 }}
        {{- end }}
  {{- end }}
