name: Release Helm Chart

on:
  push:
    tags:
      - "v*.*.*"
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Get version from tag
        id: version
        run: |
          if [ "${{ github.ref_type }}" == "tag" ]; then
            VERSION=${GITHUB_REF#refs/tags/v}
            echo "version=$VERSION" >> $GITHUB_OUTPUT
            echo "tag=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT
          else
            VERSION=$(grep '^version:' Chart.yaml | awk '{print $2}')
            echo "version=$VERSION" >> $GITHUB_OUTPUT
            echo "tag=v$VERSION" >> $GITHUB_OUTPUT
          fi

      - name: Update Chart.yaml version
        run: |
          sed -i "s/^version:.*/version: ${{ steps.version.outputs.version }}/" Chart.yaml
          cat Chart.yaml | grep version

      - name: Install Helm
        uses: azure/setup-helm@v4
        with:
          version: "latest"

      - name: Clean old dependencies
        run: |
          rm -rf charts/*.tgz

      - name: Update chart dependencies
        run: |
          helm dependency update

      - name: Package Helm chart
        run: |
          helm package .

      - name: Push to Cloudsmith
        uses: cloudsmith-io/action@7af394e0f8add4867bce109385962dafecad1b8d # v0.6.14
        with:
          api-key: ${{ secrets.CLOUDSMITH_API_KEY }}
          command: "push"
          format: "helm"
          owner: "tielbeke"
          repo: "tielbeke"
          file: "motion-tools-*.tgz"
